version: '3.8'

services:
  eureka-server:
    image: eureka-server-service
    container_name: eureka-server
    build:
      context: ./eureka-server-application
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  api-gateway-service:
    image: api-gateway-service
    container_name: api-gateway
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

  author-service:
    image: author-service
    container_name: author-service
    build:
      context: ./author-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/bookstore_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  book-service:
    image: book-service
    container_name: book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/bookstore_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  identity-service:
    image: identity-service
    container_name: identity-service
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/bookstore_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

networks:
  microservices-network:
    driver: bridge
